//! The bun backend for pmpx.
//!
//! Pure mapping: a verb plus its arguments in, one command out. It reads nothing, writes
//! nothing, and never looks at the environment -- everything the plugin is allowed to know
//! arrives in [`Context`], which the host filled in from files it already stat'd.
//!
//! Only `build` and `test` carry a `run` of their own, because `bun build` and `bun test` are
//! built-ins that shadow the scripts of the same name; no verb inserts a `--`. Both are
//! explained at the point of implementation, in `PackageManager::command`.

use std::ffi::OsString;

use pmpx_plugin::{CommandSpec, Context, Family, PackageManager, PluginError, Verb};

struct Bun;

impl PackageManager for Bun {
    fn name(&self) -> &str {
        "bun"
    }

    fn family(&self) -> Family {
        Family::NODE
    }

    fn command(
        &self,
        _ctx: &Context,
        verb: Verb,
        args: &[OsString],
    ) -> Result<CommandSpec, PluginError> {
        let spec = match verb {
            // No arguments means "install what package.json and the lockfile already say";
            // arguments mean "add these". That split is the contract's, and it is why the two
            // branches differ at all.
            Verb::Install if args.is_empty() => CommandSpec::new("bun").arg("install"),
            Verb::Install => CommandSpec::new("bun").arg("add").args(args.iter()),

            Verb::Remove => CommandSpec::new("bun").arg("remove").args(args.iter()),

            // The host flattens the script name and the rest into one argument list, so the
            // name is already the first argument and `run` is the right thing in front of it.
            // Nothing is split off and nothing is inserted -- in particular no `--`: bun
            // forwards what it does not recognise to the script, and it strips a `--` when one
            // is present, so adding one would only be noise.
            Verb::Run => CommandSpec::new("bun").arg("run").args(args.iter()),

            // `run` is not optional on this one. `bun build` is bun's own bundler, not the
            // `build` script in package.json, and it shadows it: the script is never reached.
            // Measured, with a package.json `build` script that echoes its arguments:
            //
            //     $ bun build --foo
            //     error: Missing entrypoints. What would you like to bundle?    (the bundler)
            //     $ bun run build --foo
            //     SCRIPT GOT:--foo                                              (the script)
            //
            // So `bun run build`, never `bun build`.
            Verb::Build => CommandSpec::new("bun")
                .arg("run")
                .arg("build")
                .args(args.iter()),

            // Same reason as `build`, and this one is even easier to get wrong because the
            // built-in is silent rather than an error: `bun test` runs bun's own test runner
            // over the project. Measured, with a package.json `test` script that echoes its
            // arguments:
            //
            //     $ bun test --foo
            //     (bun's test runner runs; the script is never reached)
            //     $ bun run test --foo
            //     SCRIPT GOT:--foo
            //
            // So `bun run test`, never `bun test`.
            Verb::Test => CommandSpec::new("bun")
                .arg("run")
                .arg("test")
                .args(args.iter()),

            // `update` and `add` are commands of their own and are not shadowed, so no `run`
            // goes here.
            Verb::Update if args.is_empty() => CommandSpec::new("bun").arg("update"),
            Verb::Update => CommandSpec::new("bun").arg("update").args(args.iter()),

            // `bunx` is the escape hatch itself -- it is bun's runner for a package binary and
            // takes the command as its first argument, so it is a straight forward.
            Verb::Exec => CommandSpec::new("bunx").args(args.iter()),
        };

        Ok(spec)
    }
}

/// The factory that the wrapper crate generated by crate-plugin-kit calls.
pub fn create() -> Box<dyn PackageManager> {
    Box::new(Bun)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn ctx() -> Context {
        Context {
            project_root: PathBuf::from("/tmp/proj"),
            matched: vec!["bun.lock".to_string(), "package.json".to_string()],
        }
    }

    /// The exact argv the backend gets spawned with, program first.
    fn argv(verb: Verb, args: &[&str]) -> Vec<String> {
        let args: Vec<OsString> = args.iter().map(OsString::from).collect();
        let spec = Bun.command(&ctx(), verb, &args).expect("should map");
        std::iter::once(spec.program.to_string_lossy().into_owned())
            .chain(spec.args.iter().map(|a| a.to_string_lossy().into_owned()))
            .collect()
    }

    /// The same argv without the program, for the assertions that are about the subcommand
    /// rather than about which binary runs.
    fn subcommand(verb: Verb, args: &[&str]) -> Vec<String> {
        argv(verb, args)[1..].to_vec()
    }

    #[test]
    fn install_without_arguments_installs_the_lockfile() {
        assert_eq!(argv(Verb::Install, &[]), ["bun", "install"]);
    }

    #[test]
    fn install_with_arguments_adds_dependencies() {
        assert_eq!(
            argv(Verb::Install, &["react", "zod"]),
            ["bun", "add", "react", "zod"]
        );
    }

    #[test]
    fn remove_removes_dependencies() {
        assert_eq!(argv(Verb::Remove, &["react"]), ["bun", "remove", "react"]);
    }

    /// The script name is the first argument the host flattens in, so it lands right after
    /// `run` with nothing inserted in front of it, and no `--` is added anywhere.
    #[test]
    fn run_forwards_the_script_name_and_its_arguments() {
        assert_eq!(
            argv(Verb::Run, &["dev", "--port", "3000"]),
            ["bun", "run", "dev", "--port", "3000"]
        );
        assert_eq!(argv(Verb::Run, &[]), ["bun", "run"]);
    }

    /// `bun build` is bun's bundler, not the `build` script. The `run` is what reaches the
    /// script, so it must survive in the argv -- `bun build` alone is a bundler invocation.
    #[test]
    fn build_goes_through_run_because_bun_build_is_the_bundler() {
        assert_eq!(
            argv(Verb::Build, &["--foo"]),
            ["bun", "run", "build", "--foo"]
        );
        assert_eq!(argv(Verb::Build, &[]), ["bun", "run", "build"]);

        // The regression this exists to catch: dropping `run` leaves the bundler's argv.
        assert_ne!(argv(Verb::Build, &[]), ["bun", "build"]);
        assert_eq!(subcommand(Verb::Build, &[]), ["run", "build"]);
    }

    /// `bun test` is bun's test runner, not the `test` script -- worse than `build`, since it
    /// runs something instead of failing. The `run` must be there.
    #[test]
    fn test_goes_through_run_because_bun_test_is_the_test_runner() {
        assert_eq!(
            argv(Verb::Test, &["--foo"]),
            ["bun", "run", "test", "--foo"]
        );
        assert_eq!(argv(Verb::Test, &[]), ["bun", "run", "test"]);

        // As above: without `run` this is bun's own test runner.
        assert_ne!(argv(Verb::Test, &[]), ["bun", "test"]);
        assert_eq!(subcommand(Verb::Test, &[]), ["run", "test"]);
    }

    /// The two `run`s above are the exception, not the pattern: `install`, `add`, `remove` and
    /// `update` are bun's own subcommands and are not shadowed by anything.
    #[test]
    fn the_other_verbs_do_not_insert_run() {
        assert_eq!(subcommand(Verb::Install, &[]), ["install"]);
        assert_eq!(subcommand(Verb::Install, &["zod"]), ["add", "zod"]);
        assert_eq!(subcommand(Verb::Remove, &["zod"]), ["remove", "zod"]);
        assert_eq!(subcommand(Verb::Update, &[]), ["update"]);
        assert_eq!(subcommand(Verb::Update, &["zod"]), ["update", "zod"]);
        assert_eq!(subcommand(Verb::Exec, &["vite"]), ["vite"]);
    }

    #[test]
    fn update_updates_everything_or_the_named_packages() {
        assert_eq!(argv(Verb::Update, &[]), ["bun", "update"]);
        assert_eq!(argv(Verb::Update, &["react"]), ["bun", "update", "react"]);
    }

    #[test]
    fn exec_runs_a_package_binary_through_bunx() {
        assert_eq!(
            argv(Verb::Exec, &["vite", "--host"]),
            ["bunx", "vite", "--host"]
        );
        // `bunx` is the program in the argv, not an argument to `bun`.
        assert_eq!(argv(Verb::Exec, &[]), ["bunx"]);
    }
}
